#!/bin/bash
#
# Example of a SLURM job script for Talon3
# Using Gaussian16 with GPUs
#
# Job Name: CO_gpu
# Number of cores: 28
# Number of GPU units: 2
# Number of nodes: 1
# Compute Node Type: GPU R730
# 
#SBATCH -J CO-gpu 
#SBATCH -p gpu
#SBATCH --gres=gpu:2
#SBATCH -n 28
#SBATCH -N 1

# loading modules
module load gaussian/g16-RevA.03-avx2
module load cuda/101/toolkit/10.1.243

# Settting up job
filename=CO-gpu.com
input=`echo $filename | sed 's/\(.*\)\.[^\.]*/\1/'`

# Setting up scratch 
STORAGE_DIR="/storage/scratch2/$USER/${SLURM_JOB_ID}.${input}"
GAUSS_SCRDIR=$STORAGE_DIR
export GAUSS_SCRDIR=$STORAGE_DIR
mkdir -pv $STORAGE_DIR
cd $STORAGE_DIR
cp $SLURM_SUBMIT_DIR/${filename} $STORAGE_DIR

# Running gaussian
time g16 < ${input}.com > ${input}.out

# copying output files and removing scratch
rm $STORAGE_DIR/*.rwf
cp -a $STORAGE_DIR $SLURM_SUBMIT_DIR
rm -rv $GAUSS_SCRDIR


