#!/bin/bash
#
# Example of a SLURM job script for Talon3
# NWChem version 7
#
# Job Name: NWChem_Job
# Compute Node Type: R420
# QOS: general
#SBATCH -J NWChem_Job
#SBATCH -o NWChem_job.o%j
#SBATCH -p preproduction
#SBATCH --qos general
#SBATCH -N 2
#SBATCH --ntasks-per-node 16
#SBATCH --exclusive

# Loading module
module load nwchem/7.0.0-2

# Settting up job
filename=h2o.nw
input=`echo $filename | sed 's/\(.*\)\.[^\.]*/\1/'`

# Setting up scratch 
STORAGE_DIR="/storage/scratch2/$USER/${SLURM_JOB_ID}.${input}"
GAUSS_SCRDIR=$STORAGE_DIR
mkdir -pv $STORAGE_DIR
cd $STORAGE_DIR
cp $SLURM_SUBMIT_DIR/${filename} $STORAGE_DIR

# Running Nwchem
time mpirun  -verbose  nwchem  ${input}.nw > ${input}.out

# copying output files and removing scratch
cp -a $STORAGE_DIR $SLURM_SUBMIT_DIR
rm -rf $STORAGE_DIR 
