#!/bin/bash
#
# Example of a SLURM job script for Talon3
# NWChem version 7
#
# Job Name: NWChem_Job
# Number of cores: 1
# Number of nodes: 28
# Compute Node Type: C6320
# QOS: general
#SBATCH -J NWChem_Job
#SBATCH -o NWChem_job.o%j
#SBATCH -p production
#SBATCH --qos general
#SBATCH -N 1
#SBATCH -n 28

# Loading module
module load nwchem/7.0.0

# Settting up job
filename=h2o.nw
input=`echo $filename | sed 's/\(.*\)\.[^\.]*/\1/'`

# Setting up scratch 
STORAGE_DIR="/storage/scratch2/$USER/${SLURM_JOB_ID}.${input}"
GAUSS_SCRDIR=$STORAGE_DIR
mkdir -pv $STORAGE_DIR
cd $STORAGE_DIR
cp $SLURM_SUBMIT_DIR/${filename} $STORAGE_DIR

# Running gaussian
time nwchem < ${input}.nw > ${input}.out

# copying output files and removing scratch
cp -a $STORAGE_DIR $SLURM_SUBMIT_DIR
rm -rf $STORAGE_DIR 
